ITEM.name = "Топор"
ITEM.description = "Деревянный топор с металлическим лезвием."
ITEM.model = "models/weapons/hl2meleepack/w_axe.mdl"
ITEM.class = "weapon_j_lumberjack_axe"
ITEM.weaponCategory = "tools"
ITEM.weight = 5
ITEM.maxDurability = 100
ITEM.flag = "v"
ITEM.width = 1
ITEM.height = 3
